#@TYPE: Machine
#@NAME: bananapi4-rdk-broadband
#@NEEDED_BSPLAYERS: meta-cmf-bananapi
#@DESCRIPTION: Machine configuration for running a RDK broadband on Banana Pi R4
#@RDK_FLAVOR: rdkb

require ${@bb.utils.contains('DISTRO_FEATURES','kernel6-6','conf/machine/filogic880-kernel6-6-bpi-r4.conf','conf/machine/filogic880-bpi-r4.conf',d)}

require conf/distro/include/rdk-bpi.inc 
PREFERRED_PROVIDER_hal-wifi_onewifi = "hal-wifi-generic"

MACHINEOVERRIDES .= ":mt7988"

#SDCARD supported changes.
MACHINEOVERRIDES .="${@bb.utils.contains('DISTRO_FEATURES','sdmmc',':sd','',d)}"
IMAGE_FSTYPES += "${@bb.utils.contains('DISTRO_FEATURES','sdmmc',' wic.bz2 ext4','',d)}"
<<<<<<< HEAD
KERNEL_DEVICETREE_mt7988_bpi4_sd = "${@bb.utils.contains('DISTRO_FEATURES','kernel6-6','mediatek/mt7988a-bananapi-bpi-r4.dtb','mediatek/mt7988a-bananapi-bpi-r4-sd.dtb', d)}"
=======
#KERNEL_DEVICETREE_mt7988_bpi4_sd = "mediatek/mt7988a-bananapi-bpi-r4-sd.dtb"
>>>>>>> 1629d2e (RDKBACCL-1156: Build RDKB generic image)

WKS_FILE = "${@bb.utils.contains('DISTRO_FEATURES', 'kernel6-6', \
                bb.utils.contains('DISTRO_FEATURES', 'EasyMesh', 'sdimage-EM-Bananapi_6-6.wks', 'sdimage-Bananapi_6-6.wks', d), \
                bb.utils.contains('DISTRO_FEATURES', 'EasyMesh', 'sdimage-EM-Bananapi.wks', 'sdimage-Bananapi.wks', d), d)}"
IMAGE_BOOT_FILES = "${@bb.utils.contains('DISTRO_FEATURES','sdmmc', bb.utils.contains('DISTRO_FEATURES','kernel6-6','mt7988a-bananapi-bpi-r4.dtb ${KERNEL_IMAGETYPE}','mt7988a-bananapi-bpi-r4-sd.dtb ${KERNEL_IMAGETYPE}', d),'',d)}"
do_image_wic[recrdeps] = "do_build"
#SDCARD supported Pre build bootloader
do_image_wic[depends] += " atf_bootloader_prebuild:do_deploy"

<<<<<<< HEAD
#RUST support for EasyMesh
RUST_PANIC_STRATEGY="${@bb.utils.contains('DISTRO_FEATURES','EasyMesh','abort','',d)}"

#removing itb-image class for kernel6-6
KERNEL_CLASSES_remove = "${@bb.utils.contains('DISTRO_FEATURES','kernel6-6','itb-image','',d)}"
=======
DISTRO_FEATURES:append = " rdkoss WanFailOverSupportEnable"

MACHINEOVERRIDES .= ":brodband"
>>>>>>> 1629d2e (RDKBACCL-1156: Build RDKB generic image)
