BBPATH .= ":${LAYERDIR}"
BBFILES += "\
            ${LAYERDIR}/meta*/recipes-*/*/*.bb \
            ${LAYERDIR}/meta*/recipes-*/*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
           "

BBFILE_COLLECTIONS += "cmf-bananapi"
BBFILE_PATTERN_cmf-bananapi := "^${LAYERDIR}/"

LAYERDEPENDS:cmf-bananapi = "cmf-filogic"
LAYERDEPENDS:cmf-bananapi:append = " filogic"

require ${@bb.utils.contains('DISTRO_FEATURES', 'em_extender','conf/distro/include/rdk-bpi-ap-extender.inc','conf/distro/include/rdk-bpi.inc', d)}
require ${@bb.utils.contains('DISTRO_FEATURES', 'em_extender','conf/include/rdk-bpi-ap-extender-bbmasks.inc','conf/include/rdk-bpi-bbmasks.inc', d)}

LAYERSERIES_COMPAT:cmf-bananapi = " kirkstone"

MIDDLEWARE_ARCH = "${MACHINE}"
PACKAGE_EXTRA_ARCHS_append = " ${MIDDLEWARE_ARCH}"
